# Generated by Django 5.1.3 on 2026-08-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='scope',
            field=models.CharField(choices=[('health', 'Health'), ('expense', 'Expense')], default='health', max_length=20),
        ),
    ]
