# Generated by Django 5.1.3 on 2026-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_only',
            field=models.BooleanField(default=False),
        ),
    ]
