# Generated by Django 4.2.25 on 2026-09-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_split_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='expenses.person'),
        ),
    ]
