# Generated by Django 5.1.3 on 2026-09-07 05:02

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def backfill_settled_amount(apps, schema_editor):
    """Rows already marked settled were paid in full - say so.

    Without this every historical settlement would read as "0 paid" against its
    amount, and `outstanding` (amount - settled_amount) would resurrect debts
    that were squared up long ago.
    """
    ExpenseSplit = apps.get_model('expenses', 'ExpenseSplit')
    ExpenseSplit.objects.filter(is_settled=True).update(settled_amount=F('amount'))


def unbackfill(apps, schema_editor):
    """Reversing only drops the columns; nothing to undo in the data."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expense_paid_by_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='include_in_expenses',
            field=models.BooleanField(default=False, help_text='The linked account chose to count this share as their own spending'),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='How much of this share has been paid so far', max_digits=10),
        ),
        migrations.RunPython(backfill_settled_amount, unbackfill),
    ]
