# Generated by Django 5.1.3 on 2026-09-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0011_alter_copilotcard_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copilotcard",
            name="kind",
            field=models.CharField(
                choices=[
                    ("bill_overdraw", "Upcoming bill overdraws safe-to-spend"),
                    ("category_spike", "Unusual category spend"),
                    ("subscription_renewed", "Subscription renewed"),
                    ("subscription_price_changed", "Subscription price changed"),
                    ("split_stale", "Unsettled split going stale"),
                    ("low_runway", "Low runway"),
                    ("inactive_logging", "No recent expense logged"),
                ],
                max_length=32,
            ),
        ),
    ]
