# Generated by Django 5.1.3 on 2026-09-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_expense_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='pending_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
