# Generated by Django 4.2.25 on 2026-10-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_expense_pending_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
