# Generated by Django 5.1.3 on 2026-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openrouterkey',
            options={'ordering': ['position', 'id'], 'verbose_name': 'OpenRouter key'},
        ),
        migrations.RemoveField(
            model_name='openrouterkey',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='openrouterkey',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='openrouterkey',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='openrouterkey',
            name='rate_limited_until',
        ),
        migrations.RemoveField(
            model_name='openrouterkey',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='openrouterkey',
            name='use_count',
        ),
        migrations.AddField(
            model_name='openrouterkey',
            name='position',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
