"""
Django settings for toolboxweb project.

Generated by 'django-admin startproject' using Django 5.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v+hd2#b=+@b0--x$rn*l+2nw%*pvgp@cu+9u8h1b$d$t$imfq("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['toolbox.pythonanywhere.com', '127.0.0.1', 'localhost', 'roaring-phoenix-c2dfd0.netlify.app', 'jaiparmani.github.io']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "tools",
    "expenses",
    "users",
    "health",
    "insights",
    "llm",
    "telegrambot",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "toolboxweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "toolboxweb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/toolbox/toolboxservices/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/toolbox/toolboxservices/static'
STATIC_URL = '/static/'

# REST Framework configuration
REST_FRAMEWORK = {
    # Every endpoint requires a real, authenticated user by default. Individual
    # views opt out with permission_classes=[AllowAny] only where genuinely
    # public (login, register). The user is derived from the token, never from
    # a client-supplied ?userid= — that trust has been removed.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Token auth only. Session auth is deliberately left off so that logging
    # into /admin/ in the same browser can't make the API treat those calls as
    # authenticated (and start enforcing CSRF on the frontend's writes).
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Rate limiting disabled for now
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle'
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/hour',
    #     'user': '1000/hour'
    # },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://toolbox.pythonanywhere.com",
    "https://roaring-phoenix-c2dfd0.netlify.app",
    "https://jaiparmani.github.io",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF settings for production
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://toolbox.pythonanywhere.com",
    "https://roaring-phoenix-c2dfd0.netlify.app",
    "https://jaiparmani.github.io",
]

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# CSRF settings for development
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False    # Set to False for development (HTTP)

# HSTS settings (for production with SSL)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True



# Claude API (used by the insights app)
# Set ANTHROPIC_API_KEY in the environment - never commit the key.
#   export ANTHROPIC_API_KEY="sk-ant-..."
# On PythonAnywhere put the export in ~/.bashrc and in the WSGI file.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

# claude-opus-5 is the current flagship. Thinking is on by default on this
# model, and max_tokens caps thinking + response together - hence the headroom.
ANTHROPIC_MODEL = os.environ.get('ANTHROPIC_MODEL', 'claude-opus-5')

# low | medium | high | xhigh | max. medium is plenty for summarising a month
# of metrics; raise it if the reviews feel shallow.
ANTHROPIC_EFFORT = os.environ.get('ANTHROPIC_EFFORT', 'medium')
ANTHROPIC_MAX_TOKENS = int(os.environ.get('ANTHROPIC_MAX_TOKENS', '8000'))

# OpenRouter (used by the AI features in expenses and insights)
# Keys normally live in the database and are rotated round-robin - see
#   manage.py openrouter_keys list
# This environment variable is the fallback used when no stored key is
# usable, so a fresh deployment still works before any are added.
#   export OPENROUTER_API_KEY="sk-or-v1-..."
OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'openrouter/free')

# ── Telegram bot (telegrambot app) ───────────────────────────────────────────
# The bot runs as a webhook inside this web app, so it's up whenever the backend
# is up — no separate long-polling process to keep alive (which is why the old
# standalone script kept going down on PythonAnywhere). Set these in the
# environment (PythonAnywhere: in ~/.bashrc *and* in the WSGI file); never
# commit the token.
#
#   TELEGRAM_BOT_TOKEN        BotFather token for the bot
#   TELEGRAM_WEBHOOK_SECRET   any long random string; it's the secret in the
#                             webhook URL path and the setWebhook secret_token
#   TELEGRAM_WEBHOOK_BASE_URL public https origin, e.g.
#                             https://toolbox.pythonanywhere.com (used by the
#                             set_telegram_webhook command)
#
# After setting them, register the webhook once:  python manage.py set_telegram_webhook
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_WEBHOOK_SECRET = os.environ.get('TELEGRAM_WEBHOOK_SECRET', '')
TELEGRAM_WEBHOOK_BASE_URL = os.environ.get(
    'TELEGRAM_WEBHOOK_BASE_URL', 'https://toolbox.pythonanywhere.com'
)

# ── Password-reset email (Gmail SMTP) ────────────────────────────────────────
# Where the reset link points (the frontend origin, no trailing slash). MUST be
# set to the deployed frontend in production, or links point at localhost.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Credentials come from the environment and are never committed. EMAIL_HOST_USER
# is the Gmail address; EMAIL_HOST_PASSWORD must be a Gmail *App Password*
# (Google account with 2FA, https://myaccount.google.com/apppasswords) - the
# normal account password will not authenticate over SMTP.
#
# Read with .get() rather than os.environ[...] so a deploy before the vars are
# set can't crash the whole app on import; without them, fall back to the
# console backend (the reset link prints to the server log).
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'ToolBox <noreply@toolbox.local>')
