# Generated by Django 4.2.25 on 2026-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shortcutapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
