# Generated by Django 5.1.3 on 2026-08-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('health', 'Health')], default='health', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('refused', 'Refused'), ('failed', 'Failed')], default='success', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='observations / concerns / suggestions / data_gaps')),
                ('model', models.CharField(blank=True, max_length=60)),
                ('effort', models.CharField(blank=True, max_length=20)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'scope', '-created_at'], name='insights_in_user_id_e81890_idx')],
            },
        ),
    ]
