# Generated by Django 4.2.25 on 2025-10-18 08:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI display', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon class or name', max_length=50, null=True)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('credit', 'Credit'), ('debt', 'Debt')], default='expense', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['transaction_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for UI display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('credit', 'Credit'), ('debt', 'Debt'), ('repayment', 'Repayment')], default='expense', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('lender_borrower', models.CharField(blank=True, help_text='Name of lender (for debts) or borrower (for credits)', max_length=100, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expense_receipts/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.expensecategory')),
                ('related_expense', models.ForeignKey(blank=True, help_text='Link to original debt for repayments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expense')),
                ('tags', models.ManyToManyField(blank=True, related_name='expenses', to='expenses.expensetag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='expenses_ex_user_id_713a9d_idx'), models.Index(fields=['user', 'category'], name='expenses_ex_user_id_45749f_idx'), models.Index(fields=['user', 'transaction_type'], name='expenses_ex_user_id_15d878_idx'), models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx'), models.Index(fields=['transaction_type'], name='expenses_ex_transac_bfe9c6_idx')],
            },
        ),
    ]
