# Generated by Django 5.1.3 on 2026-08-23 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_person_expensesplit_person_unique_person_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='The account this person signs in with, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_debts', to=settings.AUTH_USER_MODEL),
        ),
    ]
