# Generated by Django 5.1.3 on 2026-08-25 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_recurringrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bill_overdraw', 'Upcoming bill overdraws safe-to-spend'), ('category_spike', 'Unusual category spend'), ('subscription_renewed', 'Subscription renewed'), ('split_stale', 'Unsettled split going stale'), ('low_runway', 'Low runway')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('watch', 'Watch'), ('urgent', 'Urgent')], default='info', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('dismissed', 'Dismissed'), ('actioned', 'Actioned')], default='new', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(help_text='Plain-language explanation, citing the real figure', max_length=500)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('metric_label', models.CharField(blank=True, max_length=120)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Snapshot of the inputs used')),
                ('action_label', models.CharField(blank=True, max_length=60)),
                ('action_route', models.CharField(blank=True, help_text='Frontend route the action opens', max_length=200)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='expenses_co_user_id_38469a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dedupe_key'), name='unique_copilot_card_per_condition')],
            },
        ),
    ]
