# Generated by Django 5.1.3 on 2026-08-26 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_profiles(apps, schema_editor):
    """Give every existing user a profile (new users get one via a signal)."""
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.', 1)[0], settings.AUTH_USER_MODEL.split('.', 1)[1])
    UserProfile = apps.get_model('users', 'UserProfile')
    existing = set(UserProfile.objects.values_list('user_id', flat=True))
    UserProfile.objects.bulk_create(
        [UserProfile(user_id=uid) for uid in User.objects.exclude(id__in=existing).values_list('id', flat=True)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_profiles, migrations.RunPython.noop),
    ]
