# Generated by Django 5.1.3 on 2026-10-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlink',
            name='awaiting_confirmation_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
