# Generated by Django 4.2.25 on 2026-10-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_telegramlink_awaiting_confirmation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlink',
            name='awaiting_edit_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
