# Generated by Django 4.2.25 on 2026-10-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_telegramlink_awaiting_edit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramlink',
            name='awaiting_confirmation_id',
        ),
    ]
