name: Deploy to PythonAnywhere

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: jaiparmani/pa-utilities/.github/workflows/deploy-pythonanywhere.yml@main
    with:
      pa_working_dir: /home/toolbox/toolboxservices
      pa_domain: toolbox.pythonanywhere.com
    secrets: inherit
